
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS notes;
CREATE TABLE users (  
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100),
    UNIQUE KEY(name)
);

CREATE TABLE notes (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    userId INT UNSIGNED NOT NULL,
    label VARCHAR(100) NOT NULL DEFAULT '',
    text TEXT,
    date DATE,
    FOREIGN KEY (userId) REFERENCES users (id)
)